### ISSUE TITLE
Remove unwanted comments

### ISSUE THREAD

**Issue by malith-gammanpila** [Navoda-Jayamini/SampleReactProject2#1]
https://github.com/IT20382094/SampleReactProject2/blob/d3603d3239081014a445ae24e65441e6e33869ef/hello-world/src/App.js#L15-L28
https://github.com/IT20382094/SampleReactProject2/blob/d3603d3239081014a445ae24e65441e6e33869ef/hello-world/src/components/Hello.js#L4-L11

Please remove these kinds of comments if you don't need them actually.

**Comment by Navoda-Jayamini** [comment]
corrected
